[workspace]
members = [".", "rax-cli", "rax-jit", "rax-core", "rax-elfgen", "rax-aot", "rax-interpreter", "rax-perf"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "rax"
version.workspace = true
edition.workspace = true

[lib]
name = "rax"
path = "src/lib.rs"

[profile.release]
debug = true
lto = "fat"
panic = "abort"

[features]
default = ["ima"]
ext_i = ["rax-core/ext_i", "rax-interpreter/ext_i", "rax-aot/ext_i", "rax-jit?/ext_i"]
ext_m = ["rax-core/ext_m", "rax-interpreter/ext_m", "rax-aot/ext_m", "rax-jit?/ext_m"]
ext_a = ["rax-core/ext_a", "rax-interpreter/ext_a", "rax-aot/ext_a", "rax-jit?/ext_a"]
ext_f = ["rax-core/ext_f", "rax-interpreter/ext_f", "rax-aot/ext_f", "rax-jit?/ext_f"]
ext_d = ["rax-core/ext_d", "rax-interpreter/ext_d", "rax-aot/ext_d", "rax-jit?/ext_d"]
ext_c = ["rax-core/ext_c", "rax-interpreter/ext_c", "rax-aot/ext_c", "rax-jit?/ext_c"]
ima = ["ext_i", "ext_m", "ext_a"]
imac = ["ima", "ext_c"]
gc = ["imac", "ext_f", "ext_d"]
jit = ["dep:rax-jit"]

[dependencies]
rax-core = { path = "rax-core" }
rax-elfgen = { path = "rax-elfgen" }
rax-interpreter = { path = "rax-interpreter" }
rax-aot = { path = "rax-aot" }
rax-jit = { path = "rax-jit", optional = true, default-features = false }

[[example]]
name = "fib_interpreter"
required-features = ["ima"]

[[example]]
name = "fib_jit"
required-features = ["ima", "jit"]

[[test]]
name = "standard_elf"
required-features = ["gc"]
