[workspace]
members = [".","eth_utils"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "riscv"
version.workspace = true
edition.workspace = true

[lib]
name = "riscv"
path = "src/lib.rs"

[[bin]]
name = "riscv-cli"
path = "src/bin/riscv_cli.rs"
required-features = ["gc"]

[profile.release]
debug = true
lto = "fat"
panic = "abort"

[features]
default = ["gc"]
trace = []
ext_i = []
ext_m = []
ext_a = []
ext_f = []
ext_d = []
ext_c = []
imac = ["ext_i", "ext_m", "ext_a", "ext_c"]
gc = ["imac", "ext_f", "ext_d"]

[dependencies]
elf = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4.3"
fxhash = "0.2.1"
cranelift-codegen = "0.129.1"
cranelift-jit = "0.129.1"
cranelift-module = "0.129.1"
cranelift-native = "0.129.1"
cranelift-frontend = "0.129.1"
revm = { version = "14", features = ["std"] }
alloy-primitives = { version = "0.8", features = ["serde"] }
alloy-rlp = "0.3"
alloy-consensus = "0.2"
alloy-provider = "0.2"
alloy-transport-http = "0.2"
alloy-rpc-types = "0.2"
alloy-trie = "0.9"
url = "2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["json"] }
sha3 = "0.10"
bincode = "1.3"
clap = { version = "4.5", features = ["derive"] }
colored = "2.0"
indicatif = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
object = { version = "0.32", features = ["write"] }

[dev-dependencies]
eth_utils = { path = "./eth_utils" }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "vm_benchmark"
harness = false

[[example]]
name = "fib_ima"
required-features = ["ext_i", "ext_m", "ext_a"]

[[example]]
name = "exec_block_ima"
required-features = ["ext_i", "ext_m", "ext_a"]

[[example]]
name = "echo_ima"
required-features = ["ext_i", "ext_m", "ext_a"]

[[example]]
name = "fib_imac"
required-features = ["imac"]

[[example]]
name = "exec_block_imac"
required-features = ["imac"]

[[example]]
name = "echo_imac"
required-features = ["imac"]

[[example]]
name = "fib_gc"
required-features = ["gc"]

[[example]]
name = "exec_block_gc"
required-features = ["gc"]

[[example]]
name = "echo_gc"
required-features = ["gc"]

[[test]]
name = "block_exec_elf"
required-features = ["gc"]

[[test]]
name = "echo_elf"
required-features = ["gc"]

[[test]]
name = "fib_elf"
required-features = ["gc"]
