[workspace]
members = [".", "riscv-cli", "riscv-jit", "riscv-core", "riscv-elfgen", "riscv-aot", "riscv-interpreter", "riscv-perf"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "riscv"
version.workspace = true
edition.workspace = true

[lib]
name = "riscv"
path = "src/lib.rs"

[profile.release]
debug = true
lto = "fat"
panic = "abort"

[features]
default = ["ima"]
ext_i = ["riscv-core/ext_i", "riscv-interpreter/ext_i", "riscv-aot/ext_i", "riscv-jit?/ext_i"]
ext_m = ["riscv-core/ext_m", "riscv-interpreter/ext_m", "riscv-aot/ext_m", "riscv-jit?/ext_m"]
ext_a = ["riscv-core/ext_a", "riscv-interpreter/ext_a", "riscv-aot/ext_a", "riscv-jit?/ext_a"]
ext_f = ["riscv-core/ext_f", "riscv-interpreter/ext_f", "riscv-aot/ext_f", "riscv-jit?/ext_f"]
ext_d = ["riscv-core/ext_d", "riscv-interpreter/ext_d", "riscv-aot/ext_d", "riscv-jit?/ext_d"]
ext_c = ["riscv-core/ext_c", "riscv-interpreter/ext_c", "riscv-aot/ext_c", "riscv-jit?/ext_c"]
ima = ["ext_i", "ext_m", "ext_a"]
imac = ["ima", "ext_c"]
gc = ["imac", "ext_f", "ext_d"]
jit = ["dep:riscv-jit"]

[dependencies]
riscv-core = { path = "riscv-core" }
riscv-elfgen = { path = "riscv-elfgen" }
riscv-interpreter = { path = "riscv-interpreter" }
riscv-aot = { path = "riscv-aot" }
riscv-jit = { path = "riscv-jit", optional = true, default-features = false }

[[example]]
name = "fib_interpreter"
required-features = ["ima"]

[[example]]
name = "fib_jit"
required-features = ["ima", "jit"]

[[test]]
name = "standard_elf"
required-features = ["gc"]
