[package]
name = "riscv-jit"
version.workspace = true
edition.workspace = true

[features]
default = ["ima"]
ext_i = ["riscv-core/ext_i", "riscv-interpreter/ext_i"]
ext_m = ["riscv-core/ext_m", "riscv-interpreter/ext_m"]
ext_a = ["riscv-core/ext_a", "riscv-interpreter/ext_a"]
ext_f = ["riscv-core/ext_f", "riscv-interpreter/ext_f"]
ext_d = ["riscv-core/ext_d", "riscv-interpreter/ext_d"]
ext_c = ["riscv-core/ext_c", "riscv-interpreter/ext_c"]
ima = ["ext_i", "ext_m", "ext_a"]
imac = ["ima", "ext_c"]
gc = ["imac", "ext_f", "ext_d"]

[dependencies]
riscv-core = { path = "../riscv-core" }
riscv-interpreter = { path = "../riscv-interpreter" }
cranelift-codegen = "0.129.1"
cranelift-jit = "0.129.1"
cranelift-module = "0.129.1"
cranelift-native = "0.129.1"
cranelift-frontend = "0.129.1"
