//! RISC-V to x86-64 translator
//!
//! This module handles the translation of RISC-V instructions to x86-64 bytecode.
//! It manages translation state, register allocation, and instruction dispatch.

use crate::decode::Instruction as RiscvInstruction;
use crate::translate::x86_emitter::X86Emitter;
use crate::translate::x86_insn::X86Instruction;
use crate::translate::{instruction_translator, RegisterMapper};

/// Translation context
#[derive(Debug, Clone)]
pub struct TranslationContext<M: RegisterMapper> {
    /// Current program counter
    pub pc: u64,

    /// Register mapping
    pub register_mapping: M,

}

/// Main RISC-V to x86-64 translator
#[derive(Debug)]
pub struct RiscvToX86Translator<M: RegisterMapper> {
    /// Bytecode emitter
    emitter: X86Emitter,

    /// Translation context
    pub(crate) context: TranslationContext<M>,

    /// List of translated instructions (for debugging)
    instructions: Vec<X86Instruction>,
}

impl<M: RegisterMapper> RiscvToX86Translator<M> {
    pub fn new() -> Self {
        // Create a new register mapping
        let register_mapping = M::new();

        RiscvToX86Translator {
            emitter: X86Emitter::new(),
            context: TranslationContext {
                pc: 0,
                register_mapping,
            },
            instructions: Vec::new(),
        }
    }

    /// Get the translation context
    pub fn context(&self) -> &TranslationContext<M> {
        &self.context
    }

    /// Get mutable translation context
    pub fn context_mut(&mut self) -> &mut TranslationContext<M> {
        &mut self.context
    }

    /// Get the emitter
    pub fn emitter(&self) -> &X86Emitter {
        &self.emitter
    }

    /// Get mutable emitter
    pub fn emitter_mut(&mut self) -> &mut X86Emitter {
        &mut self.emitter
    }

    /// Complete translation
    pub fn finish(&mut self) -> Result<(), String> {
        self.emitter.apply_relocations()?;
        Ok(())
    }

    /// Add an instruction to the translation
    pub fn add_instruction(&mut self, instruction: X86Instruction) {
        self.instructions.push(instruction);
    }

    /// Emit an instruction
    pub fn emit_instruction(&mut self, instruction: &X86Instruction) -> Result<(), String> {
        match instruction {
            X86Instruction::Mov { src, dst } => self.emitter.emit_mov(src, dst),
            X86Instruction::Add { src, dst } => self.emitter.emit_add(src, dst),
            X86Instruction::Sub { src, dst } => self.emitter.emit_sub(src, dst),
            X86Instruction::Jmp { target } => self.emitter.emit_jmp(target),
            X86Instruction::Ret => {
                self.emitter.emit_ret();
                Ok(())
            }
            X86Instruction::Label { name } => {
                self.emitter.emit_label(name.clone());
                Ok(())
            }
            X86Instruction::Nop => {
                self.emitter.emit_byte(0x90);
                Ok(())
            }
            _ => Err(format!(
                "Instruction not yet implemented: {:?}",
                instruction
            )),
        }
    }

    /// Get the bytecode
    pub fn get_bytecode(&self) -> &[u8] {
        self.emitter.get_buffer()
    }

    /// Get the instruction list
    pub fn get_instructions(&self) -> &[X86Instruction] {
        &self.instructions
    }

    /// Get translation statistics
    pub fn get_stats(&self) -> TranslationStats {
        TranslationStats {
            instructions_translated: self.instructions.len(),
            bytecode_size: self.get_bytecode().len(),
        }
    }

    /// Process a RISC-V instruction through translation
    ///
    /// This is the main entry point for translating individual RISC-V instructions.
    /// Returns an error if the instruction is not yet supported.
    pub fn process_instruction(&mut self, riscv_insn: &RiscvInstruction) -> Result<(), String> {
        instruction_translator::translate_instruction(self, riscv_insn)?;
        self.context.pc += 4; // RISC-V instructions are always 4 bytes
        Ok(())
    }
}

impl<M: RegisterMapper> Default for RiscvToX86Translator<M> {
    fn default() -> Self {
        Self::new()
    }
}

/// Translation statistics
#[derive(Debug, Clone)]
pub struct TranslationStats {
    /// Number of instructions translated
    pub instructions_translated: usize,

    /// Size of generated bytecode
    pub bytecode_size: usize,

}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::aot::register_mapping::RegisterMapping;

    #[test]
    fn test_translator_creation() {
        let translator = RiscvToX86Translator::<RegisterMapping>::new();
        assert_eq!(translator.get_instructions().len(), 0);
        assert_eq!(translator.context().pc, 0);
    }

    #[test]
    fn test_translator_finish() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();
        translator.finish().unwrap();
        // Finish should complete without error
    }

    #[test]
    fn test_add_instruction() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();

        let nop = X86Instruction::Nop;

        translator.add_instruction(nop);
        assert_eq!(translator.get_instructions().len(), 1);
    }

    #[test]
    fn test_emit_nop() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();

        translator.emit_instruction(&X86Instruction::Nop).unwrap();
        assert_eq!(translator.get_bytecode()[0], 0x90);
    }

    #[test]
    fn test_add_multiple_instructions() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();

        translator.add_instruction(X86Instruction::Nop);
        translator.add_instruction(X86Instruction::Nop);

        let stats = translator.get_stats();
        assert_eq!(stats.instructions_translated, 2);
    }

    #[test]
    fn test_register_mapping_access() {
        let translator = RiscvToX86Translator::<RegisterMapping>::new();

        let _mapping = &translator.context().register_mapping;
        // Verify mapping was created
    }

    #[test]
    fn test_emit_ret() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();

        translator.emit_instruction(&X86Instruction::Ret).unwrap();
        assert_eq!(translator.get_bytecode()[0], 0xC3);
    }

    #[test]
    fn test_get_stats() {
        let mut translator = RiscvToX86Translator::<RegisterMapping>::new();

        translator.add_instruction(X86Instruction::Nop);
        translator.add_instruction(X86Instruction::Nop);

        let stats = translator.get_stats();
        assert_eq!(stats.instructions_translated, 2);
    }
}
