[package]
name = "riscv-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "riscv"
path = "src/main.rs"
required-features = ["ima"]

[features]
default = ["ima"]
ext_i = ["riscv-interpreter/ext_i", "riscv-aot/ext_i", "riscv-jit/ext_i"]
ext_m = ["riscv-interpreter/ext_m", "riscv-aot/ext_m", "riscv-jit/ext_m"]
ext_a = ["riscv-interpreter/ext_a", "riscv-aot/ext_a", "riscv-jit/ext_a"]
ext_f = ["riscv-interpreter/ext_f", "riscv-aot/ext_f", "riscv-jit/ext_f"]
ext_d = ["riscv-interpreter/ext_d", "riscv-aot/ext_d", "riscv-jit/ext_d"]
ext_c = ["riscv-interpreter/ext_c", "riscv-aot/ext_c", "riscv-jit/ext_c"]
ima = ["ext_i", "ext_m", "ext_a"]
imac = ["ima", "ext_c"]
gc = ["imac", "ext_f", "ext_d"]

[dependencies]
riscv-interpreter = { path = "../riscv-interpreter", default-features = false }
riscv-aot = { path = "../riscv-aot", default-features = false }
riscv-jit = { path = "../riscv-jit", default-features = false }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
colored = "2.0"
serde_json = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
